---
# --------------------- Add Linux Groups

- name:                 "Add Oracle Installation Group"
  group: 
    name:               "{{ oracle_user.install_group.name }}"
    gid:                "{{ oracle_user.install_group.gid }}"
    state:              present
    system:             no

- name:                 "Create ASM Linux Groups"
  group: 
    name:               "{{ item.value.name }}"
    gid:                "{{ item.value.gid }}"
    state:              present
    system:             no
  with_dict:            "{{ oracle_user.asm_groups }}"
  when:                 is_oracle_asm_installed

- name:                 "Create Database Linux Groups"
  group: 
    name:               "{{ item.value.name }}"
    gid:                "{{ item.value.gid }}"
    state:              present
    system:             no
  with_dict:            "{{ oracle_user.db_groups }}"

# --------------------- Create Oracle User

- name:                 "Load Oracle User Password"
  include_vars:
    file:               oracle_pw.yml
    name:               oracle_user_pw

- set_fact:
    oracle_groups:      "{{ lookup('flattened', oracle_user | json_query('*.*.name')) }}"
  when:                 is_oracle_asm_installed

- set_fact:
    oracle_groups:      "{{ lookup('flattened', oracle_user | json_query('db_groups.*.name')) }}"
  when:                 not is_oracle_asm_installed

- name:                 "List of groups to be assigned to oracle user"
  debug:
    var:                oracle_groups
    verbosity:          1

- name:                 "Set default group and password for Oracle user"
  user:
    name:               oracle
    comment:            "Oracle software owner"
    password:           "{{ oracle_user_pw.password }}"
    group:              "{{ oracle_user.install_group.name }}"
    groups:             "{{ oracle_user.install_group.name }},{{ oracle_groups }}"

...
