---
# ------------------------------------------------------------------------------
# Sets up a data guard environment
# ------------------------------------------------------------------------------

# -------------------- Include variables from Oracle User role

- name:                "Include variables from Oracle User role"
  include_vars:
    dir:               ../../oracle_user/vars
    files_matching:    main.yml

# -------------------- Define static listener entries

- name:                "Define static listener entries"
  blockinfile:
    path:               "{{ oracle_vars.oracle_home }}/network/admin/listener.ora"
    insertafter:        "EOF"
    marker:             "# {mark} Static Listener Entries"
    block: |
      SID_LIST_LISTENER =
        (SID_LIST =
          (SID_DESC =
            (GLOBAL_DBNAME = {{ oracle_vars.db_unique_name }}_DGMGRL.yaocm.id.au)
            (ORACLE_HOME = {{ oracle_vars.oracle_home }})
            (SID_NAME = {{ oracle_vars.sid_name }})
          )
        )

  become:               yes
  become_user:          oracle
  when:                 oracle_vars["data_guard_role"] != "observer"
  notify:
  - restart oracle listener

# --------------------- Add aliases for DG databases

- name:                 "Add Data Guard aliases to TNSNAMES file"
  blockinfile:
    path:               "{{ oracle_vars.oracle_home }}/network/admin/tnsnames.ora"
    create:             "yes"
    group:              "{{ oracle_user.install_group.name }}"
    mode:               0644
    owner:              "oracle"
    marker:             "# {mark} Data Guard Aliases"
    block:              "{{ data_guard_vars.tnsname_aliases }}"
    insertbefore:       EOF
  become:               yes
  become_user:          oracle

# --------------------- Refresh SQL scripts from GITHUB

- include_role:
    name:               common
    tasks_from:         clone_sql_ocm12c.yml


# --------------------- Get database settings off primary and standby nodes

- name:                 "Get database settings"
  command:
    cmd:                "/bin/bash get_database_settings.sh jar {{ oracle_vars.oracle_home }}"
    chdir:              "/home/oracle/sql-ocm12c/Data Guard/Create a physical standby database"
  register:             database_settings
  become:               yes
  become_user:          oracle
  changed_when:         false
  failed_when:          false
  when:                 oracle_vars["data_guard_role"] != "observer"

- name:                 "Show database settings"
  debug:
    var:                database_settings.stdout_lines
  when:                 database_settings is defined
...
