---
# ------------------------------------------------------------------------------
# Create database using SQL*Plus
# ------------------------------------------------------------------------------

- name:                 "Create database"
  block:

  - name:               "Load Oracle User Password"
    include_vars:
      file:             oracle_pw.yml
      name:             oracle_pw

# --------------------- Get latest version of SQL Scripts from repository
#
  - name:               "Get latest version of SQL Scripts from repository"
    git:
      repo:             git@github.com:dfhawthorne/sql-ocm12c.git
      dest:             /home/oracle/sql-ocm12c
      clone:            yes
      update:           yes

# --------------------- Silently create database

  - name:               "Check if database has been created"
    stat:
      get_attributes:   no
      get_checksum:     no
      path:             /opt/app/oracle/oradata/ocm12c_padstow/control01.ctl
    register:           db_status
      
  - name:               "Create database as required"
    block:
    
    - debug:
        msg:            "Place holder for creation of database"
        verbosity:      0
        
    when:               not db_status.stat.exists


  become:               yes
  become_user:          oracle
  tags:                 create_db

...
