---
# ------------------------------------------------------------------------------
# Create database using SQL*Plus
# ------------------------------------------------------------------------------

# --------------------- Ensure database entry exists in /etc/oratab

- name:                 "Ensure database entry exists in /etc/oratab"
  lineinfile:
    path:               /etc/oratab
    regexp:             '^jar:'
    line:               "jar:/opt/app/oracle/product/12.1.0/dbhome_1:N"
    insertbefore:       EOF
  become:               yes
  become_user:          root

# --------------------- Create Database using user, oracle.  

- name:                 "Create database"
  block:

  - name:               "Load Oracle User Password"
    include_vars:
      file:             oracle_pw.yml
      name:             oracle_pw

# --------------------- Get latest version of SQL Scripts from repository
#
  - name:               "Get latest version of SQL Scripts from repository"
    git:
      repo:             git@github.com:dfhawthorne/sql-ocm12c.git
      dest:             /home/oracle/sql-ocm12c
      clone:            yes
      update:           yes

# --------------------- Silently create database

# --------------------- Create  master script to create database

  - name:               "Create master script for creating database"
    template: 
      src:              create_jar_db.sh
      dest:             /tmp/create_jar_db.sh

# --------------------- Run master script

  - name:               "Run database creation script"
    command:            '/bin/sh /tmp/create_jar_db.sh'
    args:
      creates:          '/opt/app/oracle/oradata/JAR/controlfile'

# --------------------- Remove master script
       
  - name:               "Remove master creation script"
    file:
      path:             '/tmp/create_jar_db.sh'
      state:            absent


  become:               yes
  become_user:          oracle
  tags:                 create_db

...
