---
# ------------------------------------------------------------------------------
# Prepare cluster for Oracle GI 12.1 installation (Networking)
# 1. eth0 is public network
# 2. eth1 is private network
# ------------------------------------------------------------------------------

- name:                 "Prepare cluster for Oracle GI 12.1 installation (Networking)"
  block:
  
  - name:               "Configure Private LAN Interface Device"
    command:            "nmcli connection mod eth1 ifname eth1"
    when:               not ( ansible_eth1.device is defined and ansible_eth1.device == "eth1" )

  - name:               "Configure Private LAN Interface IP Address"
    command:            "nmcli connection mod eth1 ip4 {{ interconnect_address }}/24"
    when:               not ( ansible_eth1.ipv4 is defined and ansible_eth1.ipv4.address == interconnect_address )

  - name:               "Configure Private LAN Interface IP MTU"
    command:            "nmcli connection mod eth1 mtu 9000"
    when:               not ( ansible_eth1.mtu is defined and ansible_eth1.mtu == 9000 )

  - name:               "Configure Private LAN Interface IP Autoconnection"
    command:            "nmcli connection mod eth1 autoconnect yes"
    when:               not ( ansible_eth1.active is defined and ansible_eth1.active )
      
  become:               yes
  become_user:          root
  tags:                 networks
...
