---
# ============================================================================
# Ensure that the Oracle ASMLib driver is configured and enabled
#   User should be 'oracle'
#   Group should be '{{ oracle_user.asm_groups.OASM.name }}'
# ============================================================================

- name:                 "Get Oracle ASMLib Driver Configuration"
  command:              "{{ oracleasm_cmd }} configure"
  register:             oasm_config
  changed_when:         false

- name:                 "OracleASM configuration"
  debug:
    var:                oasm_config.stdout_lines
    verbosity:          1

- name:                 "Set Owner for Oracle ASMLib Driver"
  command:              "{{ oracleasm_cmd }} configure -u oracle"
  when:                 oasm_config.stdout_lines[1] != "ORACLEASM_UID=oracle"

- name:                 "Set test for ASMLib correct group"
  set_fact:
    asmlib_correct_group:
                        "ORACLEASM_GID={{ oracle_user.asm_groups.OSASM.name }}"

- name:                 "Set Group for Oracle ASMLib Driver"
  command:              "{{ oracleasm_cmd }} configure -g {{ oracle_user.asm_groups.OSASM.name }}"
  when:                 oasm_config.stdout_lines[2] != asmlib_correct_group

- name:                 "Enable Oracle ASMLib Driver"
  command:              "{{ oracleasm_cmd }} configure -e"
  when:                 oasm_config.stdout_lines[0] == "ORACLEASM_ENABLED=false"

# ============================================================================
# Ensure that the Oracle ASMLib Driver is initialized and loaded
# ============================================================================

- name:                 "Check Oracle ASMLib Driver Status"
  command:              "{{ oracleasm_cmd }} status"
  register:             oasm_status
  changed_when:         false
  failed_when:          false
  no_log:               true

- name:                 "Status of Oracle ASMLib Driver"
  debug:
    var:                oasm_status.stdout_lines
    verbosity:          1

- name:                 "Load and initialize Oracle ASMLib Driver"
  command:              "{{ oracleasm_cmd }} init"
  when:                 oasm_status.stdout_lines[0] is match("Checking if ASM is loaded. no")

- name:                 "Verify Oracle ASMLib Driver is loaded and initialized"
  command:              "{{ oracleasm_cmd }} status"
  register:             oasm_status
  changed_when:         false

...
