---
# ------------------------------------------------------------------------------
# Install necessary packages for Oracle ASMLib file system driver
# -----------------------------------------------------------------------------
- name: "Install Oracle ASMLib RPM"
  yum:
    name: kmod-oracleasm
    state: present

- name: "Install other packages for ASM"
  yum:
    name: oracleasm-support
    state: present

...
