---
- name: "Install Oracle ASMLib RPM"
  yum:
    name: http://download.oracle.com/otn_software/asmlib/oracleasmlib-2.0.12-1.el7.x86_64.rpm
    state: present

- name: "Install other packages for ASM"
  yum:
    name: oracleasm-support
    state: present

...
