---
# tasks file for asmlib
- name:                 "Install and configure ASMLib"
  block:
    - import_tasks:     install_asmlib_sw.yml
    - import_tasks:     configure_oracleasm.yml
    - import_tasks:     init_iscsi_disk_asm.yml
  become:               yes
  become_user:          root
...
