---
# ==============================================================================
# Initialise a disk device only if it is not already an ASM disk
#   Variable oracleam_cmd is inherited from global variables
# ==============================================================================

- name:                 "Initialise a disk device only if it is not already an ASM disk"
  block:

  - name:               "Ensure that there is one partition that occupies whole disk {{ oasm_disk.dev }}"
    parted:
      device:           "{{ oasm_disk.dev }}"
      number:           1
      state:            present
      label:            msdos
      part_type:        primary
      part_start:       0%
      part_end:         100%

  - name:               "Query status of disk {{ oasm_disk.dev }}1"
    command:            "{{ oracleasm_cmd }} querydisk {{ oasm_disk.dev }}1"
    changed_when:       false
    failed_when:        false
    no_log:             true
    register:           oasm_disk_status

  - name:               "Status of disk {{ oasm_disk.dev }}1"
    debug:
      var:              oasm_disk_status.stdout_lines
      verbosity:        0

  - name:               "Initialize {{ oasm_disk.dev }}1 as {{ oasm_disk.disk }}"
    command:            "{{ oracleasm_cmd }} createdisk {{ oasm_disk.disk }} {{ oasm_disk.dev }}1"
    when:               oasm_disk_status.stdout_lines[0] is match("Device .* is not marked as an ASM disk")

  become:               yes
  become_user:          root
  tags:                 oracleasm_init_disk
