---
# ------------------------------------------------------------------------------
# Create the minimal installation directories needed to install Oracle Grid
#   Infrastructure (GI).
#
# The ownership of these directories is set to oracle and its installation
#   group. This is to be done ONLY ONCE as the root scripts change the
#   persmissions later during software installation.
# ------------------------------------------------------------------------------

# --------------------- Created the directories needed for installation

- name:                 "Created the directories needed for installation"
  include_role:
    name:               common
    tasks_from:         add_new_install_dir.yml
  loop:
    -                   "{{ oracle_gi.inventory_location | dirname }}"
    -                   "{{ oracle_gi.oracle_base }}"
  loop_control:
    loop_var:           install_dir
...
