---
# ------------------------------------------------------------------------------
# Prepare cluster for Oracle GI 12.1 installation (Networking)
# 1. eth0 is public network
# 2. eth1 is private network
# ------------------------------------------------------------------------------

- name:                 "Prepare cluster for Oracle GI 12.1 installation (Networking)"
  block:
  
  - name:               "Configure Private LAN Interface Device"
    command:            "nmcli connection mod eth1 ifname eth1 ip4 {{ interconnect_address }}/24 mtu 9000 autoconnect yes ipv4.method manual"
    changed_when:       false
      
  become:               yes
  become_user:          root
  tags:                 networks
...
