---
# ==============================================================================
# Manage User Equivalency between all nodes of a cluster
# (1) Generate SSH keys on first node only
# (2) Copy SSH private and public keys back to Ansible server
# (3) Add public key to authorized keys
# (4) Add nodes of cluster to known hosts file
# ==============================================================================

# --------------------- Generate SSH keys on first node only 

- name:                 "Generate and copy SSH keys for first node only"
  user:
    name:               oracle
    generate_ssh_key:   yes
  when:                 first_node

# --------------------- Copy SSH private and public keys back to Ansible server

- block:
  - name:               "Retrieve SSH Public Key from first node only"
    fetch:
      src:              /home/oracle/.ssh/id_rsa.pub
      dest:             /etc/ansible/keys/redfern/
      flat:             yes

  - name:               "Retrieve SSH Private Key from first node only"
    fetch:
      src:              /home/oracle/.ssh/id_rsa
      dest:             /etc/ansible/keys/redfern/
      flat:             yes

  when:                 first_node

# --------------------- Copy SSH private and public keys from the Ansible server
#                         to other nodes in the cluster

- block:
  - name:               "Use SSH Public Key from first node"
    copy:
      dest:             /home/oracle/.ssh/
      src:              /etc/ansible/keys/redfern/id_rsa.pub

  - name:               "Use SSH Private Key from first node"
    copy:
      dest:             /home/oracle/.ssh/
      src:              /etc/ansible/keys/redfern/id_rsa

  when:                 not first_node

# --------------------- Add public key to authorized keys

- name:                 "Add public key to authorized keys"
  authorized_key:
    user:               oracle
    state:              present
    key:                "{{ lookup('file', '/etc/ansible/keys/redfern/id_rsa.pub') }}"

# --------------------- Add nodes of cluster to known hosts file

- include_tasks:        add_host_to_known_hosts.yml
  with_items:
  - "{{ ansible_fqdn }}"
  - "{{ ansible_hostname }}"
  loop_control:
    loop_var:           new_host_name
  become:               yes
  become_user:          oracle
  tags:                 add_host_to_known_hosts

...
