---
# ------------------------------------------------------------------------------
# Install the following modules on all systems:
# (1) nscd for DNS caching
# (2) pexpect for the Ansible pexpect module
# (3) perl for TFA on Oracle systems
# ------------------------------------------------------------------------------

# ---------------- Install NSCD

- name:            "Install DNS caching module (nscd) on Ubuntu"
  apt:
    name:          nscd
    state:         latest
  become:          yes
  become_user:     root
  when:            ansible_distribution == "Ubuntu"

- name:            "Install DNS caching module (nscd) on OEL"
  yum:
    name:          nscd
    state:         latest
  become:          yes
  become_user:     root
  when:            ansible_distribution == "OracleLinux"

# ---------------- Install PEXPECT

- name:            "install Python module PEXPECT on Ubuntu systems"
  apt:
    name:          python-pexpect
    state:         latest
  become:          yes
  become_user:     root
  when:            ansible_distribution == "Ubuntu"

- name:            "Install Python module PEXPECT on OEL 7+ systems"
  block:

  - name:          "Ensure old version of PEXPECT is not installed on OEL 7+ systems"
    yum:
      name:        pexpect
      state:       absent

  - name:          "Install SETUP_TOOLS for EASY_INSTALL on OEL 7+ systems"
    yum:
      name:        python-setuptools
      state:       latest

  - name:          "Install PIP on OEL 7+ systems"
    easy_install:
      name:        pip
      state:       latest

  - name:          "Use PIP to install PEXPECT on OEL 7+ systems"
    pip:
      name:        pexpect
      state:       latest
  become:          yes
  become_user:     root
  when:            ansible_distribution == "OracleLinux" and ansible_distribution_major_version > '6'

- name:            "Ensure old version of PEXPECT is installed on OEL 6 systems"
  yum:
    name:          pexpect
    state:         latest
  become:          yes
  become_user:     root
  when:            ansible_distribution == "OracleLinux" and ansible_distribution_major_version == '6'

# --------------------- Install Perl

- name:                 "Install Perl on Oracle Systems"
  yum:
    name:               perl
    state:              latest
  become:               yes
  become_user:          root
  when:                 ansible_distribution == "OracleLinux"
  tags:                 install_perl

...
